addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow
      # aeroo
      # - debhelper
      # - autotools-dev
      # - cups-ppdc
      # - libcups2-dev
      # - cups
      # - imagemagick
      # FE
      - mercurial
      - python-dev
      - swig
      - libffi-dev
      - libssl-dev
      - python-m2crypto
      - python-httplib2

language: python

# new options suggested by Alexandre Fayolle
sudo: false
cache: pip

python:
  - "2.7"

# for aeroo
# we make this way becasue we could not get it work in other way, we need cups
before_install:
  # aeroo
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcups2-dev
  # - sudo apt-get install -qq debhelper autotools-dev cups-ppdc libcups2-dev cups imagemagick
    # ghostscript
  - pip install httplib2 pycups==1.9.68

  # FE
  # - sudo apt-get install -qq mercurial python-dev swig libffi-dev libssl-dev python-m2crypto python-httplib2
  - pip install -r requirements.txt
  - pip install -r requirements2.txt

env:
  # TODO enable lint check
  - VERSION="8.0" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  # aeroo reports
  - git clone https://github.com/aeroo/aeroo_reports.git ${HOME}/aeroo_reports
  - pip install git+https://github.com/aeroo/aeroolib.git@master pycups==1.9.68

  # odoo addons adhoc
  - git clone https://github.com/ingadhoc/odoo-addons.git ${HOME}/odoo-addons

  # odoo addons argentina
  - git clone https://github.com/ingadhoc/odoo-argentina.git ${HOME}/odoo-argentina

  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - pip install -r requirements.txt
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  coveralls
